apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-persistance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sabine22-alt/ms-persistance
    targetRevision: main
    path: k8s/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: ms-persistance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
